# 异常体系

## 1.异常的处理方式
异常有捕获处理和抛出处理两种方式。<br>

### 1.捕获处理
```java
try {
  //有可能出错的代码；
} catch(/*异常对象*/) {
  //处理异常；
}
```
注意``try...catch``的执行顺序，当catch捕捉的异常后，执行catch中的代码，执行完毕后便退出``try...catch``语句。<br>

实例：<br>
```java
try {
			int num = 5/0;
		} catch(ArithmeticException ae) {
			System.out.println("除数不能为零");
		}
```

### 2.抛出异常
当我们不想管异常时，或没有能力处理异常时，可以使用抛出异常。<br>
使用``throws``关键字抛出异常。<br>
例如：<br>
```java
public static void function() throws IOExcepution {
  FileWriter fw = new FileWriter("a.txt");
}
```

## 2.Throwable
为了使异常处理更灵活，我们可以使用异常对象的方法：<br>

### 1.Throwable.getMessage
```java
String	getMessage();//Returns the detail message string of this throwable.
```

### 2.Throwable.toString
```java
String	toString();//Returns a short description of this throwable.
```

### 3.Throwable.printStackTrace
```java
void	printStackTrace();//Prints this throwable and its backtrace to the standard error stream.
```

## 3.finally
``finally``组合``try...catch``使用，用于释放资源和收尾工作，``finally``代码一定会执行。<br>
```java
try {
  //Exception
} catch(/*异常对象*/) {
  //处理异常
} finally {
  //释放资源
  //清理垃圾
}
```

## 4.自定义异常
我们自定义异常可以有两种选择：<br>
- 1.运行时异常
- 2.编译时异常
- 3.自定义异常

特别的对于编译时异常，我们需要手动抛出。<br>

实例：<br>
```java
public static void main(String[] args) {
  try {
    checkScore(110);
  } catch (Exception e) {
    System.out.println(e.getMessage());
  }
}

public static boolean checkScore(int score) /*throw MyExcepton*/ {
  if(score < 0 || score > 100) {
    //throw new RuntimeException("error");
    //throw new Exception("error");
    throw new MyException("error");
  }
  System.out.println("OK");
}
```

```java
package com.noble;

public class MyExcepton extends RuntimeException{

  public MyExcepton() {
    super();
  }

  public MyException(String message) {
    super(message);
  }
}
```





























#
